-- upgrade --
CREATE TABLE IF NOT EXISTS "baseforqueries" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "target_class" VARCHAR(50) NOT NULL,
    "data" JSON NOT NULL
);
CREATE TABLE IF NOT EXISTS "drug" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "generic_name" VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "brandname" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(100)  UNIQUE,
    "drug_id" INT NOT NULL REFERENCES "drug" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "category" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(100)  UNIQUE,
    "drug_id" INT NOT NULL REFERENCES "drug" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "drugclass" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(100)  UNIQUE,
    "drug_id" INT NOT NULL REFERENCES "drug" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "therapeuticuse" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "name" VARCHAR(100)  UNIQUE,
    "drug_id" INT NOT NULL REFERENCES "drug" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSON NOT NULL
);
